version: '3'

services:
  web: &python
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    container_name: djangoapp
    volumes:
      - ./app/:/usr/src/app/
      - ~/.aws/:/root/.aws:ro
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev-sample
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=database1_role
      - POSTGRES_PASSWORD=database1_password
      - POSTGRES_DB=database1

volumes:
  postgres_data:
  node-modules: